apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp-probes
  name: myapp-probes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp-probes
  template:
    metadata:
      labels:
        app: myapp-probes
    spec:
      containers:
      - image: captain7141/app1:v1.0
        name: loginapp2
        resources: {}
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 30
          successThreshold: 1
          failureThreshold: 1
          httpGet:
              path: /
              port: 80
        readinessProbe:
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          httpGet:
              path: /
              port: 80
