# Deployment with service and HPA configured.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-hpa
spec:
  selector:
    matchLabels:
      run: deploy-hpa
  replicas: 1
  template:
    metadata:
      labels:
        run: deploy-hpa
    spec:
      containers:
      - name: deploy-hpa
        image: captain7141/app1:v1.0
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 400m
            memory: "400Mi"
          requests:
            cpu: 100m
            memory: "100Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: deploy-hpa
  labels:
    run: deploy-hpa
spec:
  ports:
  - port: 80
  selector:
    run: deploy-hpa

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: deploy-hpa
spec:
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deploy-hpa
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50
